apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "<%=pkgName%>.fullname" . }}
  labels:
    app: {{ template "<%=pkgName%>.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "<%=pkgName%>.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "server"
          ]
          ports:
            - name: server
            containerPort: {{ .Values.service.serverPort }}
            protocol: TCP
            - name: metrics
            containerPort: {{ .Values.service.metricsPort }}
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.service.healthPort }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.service.healthPort }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: gateway
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: [
            "gateway"
          ]
          ports:
            - containerPort: {{ .Values.service.gatewayPort }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}